import type { DetailPageConfig, DetailPageType } from '@/components/job-detail/types';

const sharedSections: DetailPageConfig['sections'] = [
  { id: 'overview', label: 'Overview' },
  { id: 'important-dates', label: 'Important Dates' },
  { id: 'vacancy', label: 'Vacancy' },
  { id: 'eligibility', label: 'Eligibility' },
  { id: 'important-links', label: 'Important Links' },
  { id: 'faq', label: 'FAQ' },
];

export const detailPageConfigs: Record<DetailPageType, DetailPageConfig> = {
  jobs: {
    pageType: 'jobs',
    listingHref: '/jobs',
    listingLabel: 'Jobs',
    atGlanceTitle: 'Job Summary',
    actionTitle: 'Apply Online',
    actionDescription: 'Application is open district wise.',
    actionButtonLabels: ['Apply Online', 'Official Notification', 'Official Website'],
    timelineTitle: 'Key Dates',
    shareTitle: 'Share',
    sections: [
      { id: 'overview', label: 'Overview' },
      { id: 'important-dates', label: 'Important Dates' },
      { id: 'eligibility', label: 'Eligibility' },
      { id: 'vacancy', label: 'Vacancy' },
      { id: 'important-links', label: 'Important Links' },
      { id: 'how-to-apply', label: 'How To Apply' },
      { id: 'faq', label: 'FAQ' },
    ],
    sidebarWidgets: ['related', 'share'],
    embeddedSections: {
      ageLimitTitle: 'Age Limit (As on 01 July 2026)',
      applicationFeeTitle: 'Application Fee',
      selectionProcessTitle: 'Selection Process',
    },
    relatedContentTitle: 'Related Updates',
    newsletterTitle: 'Get Updates on Email',
    newsletterDescription: 'Subscribe to get fresh official updates directly in your inbox.',
    newsletterButtonText: 'Subscribe',
    helpTitle: 'Need Help?',
    helpDescription: 'Our support team can help you find official links and important dates.',
    helpHref: '/contact-us',
    helpButtonText: 'Contact Support',
  },
  results: {
    pageType: 'results',
    listingHref: '/results',
    listingLabel: 'Results',
    atGlanceTitle: 'Job Summary',
    actionTitle: 'Download Result',
    actionDescription: 'Use the official result link for scorecard and merit list updates.',
    actionButtonLabels: ['Download Result', 'Official Website'],
    timelineTitle: 'Key Dates',
    shareTitle: 'Share',
    sections: [
      { id: 'overview', label: 'Overview' },
      { id: 'important-dates', label: 'Important Dates' },
      { id: 'important-links', label: 'Important Links' },
      { id: 'faq', label: 'FAQ' },
    ],
    sidebarWidgets: ['actions', 'timeline', 'related', 'share', 'newsletter', 'help'],
    embeddedSections: {
      ageLimitTitle: 'Age Limit',
      applicationFeeTitle: 'Application Fee',
      selectionProcessTitle: 'Selection Process',
    },
    relatedContentTitle: 'Related Updates',
    newsletterTitle: 'Get Updates on Email',
    newsletterDescription: 'Subscribe to get fresh official updates directly in your inbox.',
    newsletterButtonText: 'Subscribe',
    helpTitle: 'Need Help?',
    helpDescription: 'Our support team can help you find official links and important dates.',
    helpHref: '/contact-us',
    helpButtonText: 'Contact Support',
  },
  'admit-cards': {
    pageType: 'admit-cards',
    listingHref: '/admit-cards',
    listingLabel: 'Admit Cards',
    atGlanceTitle: 'Job Summary',
    actionTitle: 'Download Admit Card',
    actionDescription: 'Use the official portal to download and verify hall ticket details.',
    actionButtonLabels: ['Download Admit Card', 'Official Website'],
    timelineTitle: 'Key Dates',
    shareTitle: 'Share',
    sections: sharedSections,
    sidebarWidgets: ['actions', 'timeline', 'related', 'share', 'newsletter', 'help'],
    embeddedSections: {
      ageLimitTitle: 'Age Limit',
      applicationFeeTitle: 'Application Fee',
      selectionProcessTitle: 'Selection Process',
    },
    relatedContentTitle: 'Related Updates',
    newsletterTitle: 'Get Updates on Email',
    newsletterDescription: 'Subscribe to get fresh official updates directly in your inbox.',
    newsletterButtonText: 'Subscribe',
    helpTitle: 'Need Help?',
    helpDescription: 'Our support team can help you find official links and important dates.',
    helpHref: '/contact-us',
    helpButtonText: 'Contact Support',
  },
  'answer-keys': {
    pageType: 'answer-keys',
    listingHref: '/answer-keys',
    listingLabel: 'Answer Keys',
    atGlanceTitle: 'Job Summary',
    actionTitle: 'Download Answer Key',
    actionDescription: 'Check provisional, final, and objection-related official updates.',
    actionButtonLabels: ['Download Answer Key', 'Official Website'],
    timelineTitle: 'Key Dates',
    shareTitle: 'Share',
    sections: [
      { id: 'overview', label: 'Overview' },
      { id: 'important-dates', label: 'Important Dates' },
      { id: 'important-links', label: 'Important Links' },
      { id: 'faq', label: 'FAQ' },
    ],
    sidebarWidgets: ['actions', 'timeline', 'related', 'share', 'newsletter', 'help'],
    embeddedSections: {
      ageLimitTitle: 'Age Limit',
      applicationFeeTitle: 'Application Fee',
      selectionProcessTitle: 'Selection Process',
    },
    relatedContentTitle: 'Related Updates',
    newsletterTitle: 'Get Updates on Email',
    newsletterDescription: 'Subscribe to get fresh official updates directly in your inbox.',
    newsletterButtonText: 'Subscribe',
    helpTitle: 'Need Help?',
    helpDescription: 'Our support team can help you find official links and important dates.',
    helpHref: '/contact-us',
    helpButtonText: 'Contact Support',
  },
  syllabus: {
    pageType: 'syllabus',
    listingHref: '/syllabus',
    listingLabel: 'Syllabus',
    atGlanceTitle: 'Job Summary',
    actionTitle: 'View Syllabus',
    actionDescription: 'Check syllabus, topics, and official preparation details.',
    actionButtonLabels: ['View Syllabus', 'Official Website'],
    timelineTitle: 'Key Dates',
    shareTitle: 'Share',
    sections: [
      { id: 'overview', label: 'Overview' },
      { id: 'eligibility', label: 'Eligibility' },
      { id: 'important-links', label: 'Important Links' },
      { id: 'faq', label: 'FAQ' },
    ],
    sidebarWidgets: ['actions', 'related', 'share', 'newsletter', 'help'],
    embeddedSections: {
      ageLimitTitle: 'Age Limit',
      applicationFeeTitle: 'Application Fee',
      selectionProcessTitle: 'Selection Process',
    },
    relatedContentTitle: 'Related Updates',
    newsletterTitle: 'Get Updates on Email',
    newsletterDescription: 'Subscribe to get fresh official updates directly in your inbox.',
    newsletterButtonText: 'Subscribe',
    helpTitle: 'Need Help?',
    helpDescription: 'Our support team can help you find official links and important dates.',
    helpHref: '/contact-us',
    helpButtonText: 'Contact Support',
  },
  schemes: {
    pageType: 'schemes',
    listingHref: '/schemes',
    listingLabel: 'Schemes',
    atGlanceTitle: 'Job Summary',
    actionTitle: 'Official Details',
    actionDescription: 'Check eligibility, benefits, and official application details.',
    actionButtonLabels: ['Official Website', 'Official Notification'],
    timelineTitle: 'Key Dates',
    shareTitle: 'Share',
    sections: [
      { id: 'overview', label: 'Overview' },
      { id: 'eligibility', label: 'Eligibility' },
      { id: 'important-links', label: 'Important Links' },
      { id: 'faq', label: 'FAQ' },
    ],
    sidebarWidgets: ['actions', 'related', 'share', 'newsletter', 'help'],
    embeddedSections: {
      ageLimitTitle: 'Age Limit',
      applicationFeeTitle: 'Application Fee',
      selectionProcessTitle: 'Selection Process',
    },
    relatedContentTitle: 'Related Updates',
    newsletterTitle: 'Get Updates on Email',
    newsletterDescription: 'Subscribe to get fresh official updates directly in your inbox.',
    newsletterButtonText: 'Subscribe',
    helpTitle: 'Need Help?',
    helpDescription: 'Our support team can help you find official links and important dates.',
    helpHref: '/contact-us',
    helpButtonText: 'Contact Support',
  },
};

export function getDetailPageConfig(pageType: DetailPageType) {
  return detailPageConfigs[pageType];
}
